Fixed two javac build errors when compiling with JDK 7: [gwt.javac] ~/smartgwt/trunk/main/src/com/smartgwt/client/bean/types/EnumValueType.java:24: error: name clash: <T#1>registerValueType(Class<T#1>) in EnumValueType and <T#2>registerValueType(Class<T#2>) in OtherValueType have the same erasure, yet neither hides the other [gwt.javac]     public static <T extends Enum<T>> void registerValueType (Class<T> klass) { [gwt.javac]                                            ^ [gwt.javac]   where T#1,T#2 are type-variables: [gwt.javac]     T#1 extends Enum<T#1> declared in method <T#1>registerValueType(Class<T#1>) [gwt.javac]     T#2 extends Object declared in method <T#2>registerValueType(Class<T#2>) [gwt.javac] ~/smartgwt/trunk/main/src/com/smartgwt/client/bean/types/JsoValueType.java:28: error: name clash: <T#1>registerValueType(Class<T#1>) in JsoValueType and <T#2>registerValueType(Class<T#2>) in OtherValueType have the same erasure, yet neither hides the other [gwt.javac]     public static <T extends JavaScriptObject> void registerValueType (Class<T> klass) { [gwt.javac]                                                     ^ [gwt.javac]   where T#1,T#2 are type-variables: [gwt.javac]     T#1 extends JavaScriptObject declared in method <T#1>registerValueType(Class<T#1>) [gwt.javac]     T#2 extends Object declared in method <T#2>registerValueType(Class<T#2>)
Related:
* http://stackoverflow.com/questions/14002965/java-name-clash-have-the-same-erasure-neither-hides-the-other
* http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6793555
* https://wiki.ubuntu.com/JavaTeam/Java7Default#Language_Handling_Changes

[dt]